DATASET_CONFIGS:
    DATASET_NAME: CIFAR-10
    DATASET_PATH: ./temp/data


MODEL_CONFIGS:
    MODEL_NAME: SIMPLE-CNN
    NUM_CLASSES: 10


TRAIN_CONFIGS:
    RUN_DEVICE: auto
    LOCAL_EPCH: 15
    BATCH_SIZE: 32
    LEARN_RATE: 0.001
    OPTIMIZER: ADAM  
    CRITERION: CROSSENTROPY         # Options: [CROSSENTROPY, NLLL]

CHANGE_CONFIGS:

    - SOURCE_LABEL: 0
      TARGET_LABEL: 8

    - SOURCE_LABEL: 8
      TARGET_LABEL: 0